### PR TITLE
support node 10+

### PR DESCRIPTION
**Pull request by sevenbitbyte**
Update nan usage

### CODE REVIEW

**Comment by valpackett** [comment]
Still an error with node 14:

```
/home/greg/.cache/node-gyp/14.5.0/include/node/v8.h:197:5: error: static_assert failed due to requirement 'std::is_base_of<v8::Context, v8::Object>::value' "type check"
    static_assert(std::is_base_of<T, S>::value, "type check");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/BluetoothHciSocket.cpp:482:18: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::Object>' requested here
        obj->Set(obj, Nan::New("devUp").ToLocalChecked(), Nan::New<Boolean>(devUp));
                 ^
```

**Comment by adi1525** [comment]
Hi, 
Very thank you for this patch.

I get v8 error on node 10.22.0

/home/adrian/.cache/node-gyp/10.22.0/include/node/v8.h:169:37: **error: cannot convert ‘v8::Object*’ to ‘v8::Context* volatile’ in assignment**
 
Regards,
Adrian

**Comment by adi1525** [comment]
Thank you!
It works on node 10.16.3

You saved me few days for debugging. ;)

Regards,
Adrian

**Comment by elggem** [comment]
It worked on Node 10.22.0! When I finally found this it was like magic. 
Who can we ping to merge this?

**Comment by rzr** [comment]
Is this issue also relevant for this release:

https://www.npmjs.com/package/@abandonware/bluetooth-hci-socket/v/0.5.3-6

**Comment by rzr** [comment]
Feel free to comment this related ticket:

https://github.com/abandonware/node-bluetooth-hci-socket/issues/9
