### ISSUE TITLE
Master branch fails to build on FreeBSD 12.0

### ISSUE THREAD

**Issue by cusspvz** [sandeepmistry/node-bluetooth-hci-socket#113]
```
../src/BluetoothHciSocket.cpp:276:42: error: no matching member function for call to 'NewInstance'
../../nan/nan.h:1045:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
  Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

**Comment by cusspvz** [comment]
Linked with https://github.com/noble/bleno/issues/438
